# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'

target 'SeatSnacks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeatSnacks

  target 'SeatSnacksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeatSnacksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
